# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-01-21 09:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MISapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='membertable',
            name='password',
            field=models.CharField(default='DEFAULT VALUE', max_length=200),
        ),
    ]
