# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-01-21 09:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MISapp', '0002_membertable_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='membertable',
            name='birthday',
            field=models.CharField(default='DEFAULT VALUE', max_length=200),
        ),
        migrations.AddField(
            model_name='membertable',
            name='gender',
            field=models.CharField(default='DEFAULT VALUE', max_length=200),
        ),
        migrations.AddField(
            model_name='membertable',
            name='name',
            field=models.CharField(default='DEFAULT VALUE', max_length=200),
        ),
        migrations.AlterField(
            model_name='membertable',
            name='email',
            field=models.CharField(default='DEFAULT VALUE', max_length=200),
        ),
    ]
